export const ROUTES = {
  home: "/",
  books: "/books",
  book: (slug: string) => `/books/${slug}`,
  categories: "/categories",
  category: (slug: string) => `/categories/${slug}`,
  authors: "/authors",
  author: (slug: string) => `/authors/${slug}`,
  cart: "/cart",
  checkout: "/checkout",
  search: "/search",
  pod: "/pod",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  profile: "/profile",
  orders: "/orders",
  order: (id: string) => `/orders/${id}`,
  wishlist: "/wishlist",
  podOrders: "/pod-orders",
} as const;
