# Generated by Django 5.0.6 on 2026-06-17 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PODSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('paper_size', models.CharField(max_length=50)),
                ('binding', models.CharField(max_length=50)),
                ('cover_type', models.CharField(max_length=50)),
                ('color_mode', models.CharField(max_length=20)),
                ('price_per_page', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_pages', models.PositiveIntegerField(default=1)),
                ('max_pages', models.PositiveIntegerField(default=500)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'POD Specification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PODOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=200)),
                ('page_count', models.PositiveIntegerField()),
                ('copies', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('printing', 'Printing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_orders', to=settings.AUTH_USER_MODEL)),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pod.podspecification')),
            ],
            options={
                'verbose_name': 'POD Order',
                'ordering': ['-created_at'],
            },
        ),
    ]
